~Version Information Block
VERS .                 2.00:  CWLS LOG ASCII STANDARD - VERSION 2.00
WRAP .                   NO:  One line per depth step
~Well Information Block
#MNEM.UNIT        Data Type   Information
#---------- ----------------  -----------
STRT .           99999.0000:  START DEPTH
STOP .               0.0000:  STOP DEPTH
STEP .               0.0000:  STEP
NULL .              -999.25:  NULL VALUE
COMP .          Lam Son JOC:  COMPANY
WELL .          02/97-DD-1X:  WELL
FLD  .              Dong Do:  FIELD
LOC  .     Cuu Long Basin, Offshore Vietn:  LOCATION
CTRY .                     :  COUNTRY
STAT .     Offshore Vietnam:  STATE
CNTY .          Adriatic XI:  COUNTY
SRVC .                  SCH:  SERVICE COMPANY
DATE .                     :  DATE
API  .                     :  API NUMBER
UWI  .                     :  UNIQUE WELL ID
~Curve Information Block
#MNEM.UNIT         API CODE   Curve Description
#---------- ----------------  -----------------
DEPTH.                     :  
~Parameter Information Block
#MNEM.UNIT            Value   Description
#---------- ----------------  -----------
PROJECT.             ThuyPham:  
SET  .          AUDIT_TRAIL:  
LATITUDE.             10.11502:  Latitude/Northing
LONGITUDE.            108.55532:  Longitude/Easting
PERMANENT_DATUM.       Mean Sea Level:  Permanent Datum
~Other Information Block
A20170703_063357_00000A801141DAC:
0|2017-07-03:06:33:57|thuyp|file import|file import|Importing 02_97-DD-1X
PARAMETER|INPUT||FILE_IN|"C:/Users/thuyp/AppData/Roaming/Skype/My Skype Received Files/02_97-DD-1X.las"
PARAMETER|INPUT||UNIT_CONVERT|Yes
CONSTANT|OUTPUT||APDAT|UNKNOWN.APDAT
CONSTANT|OUTPUT||CNTY|UNKNOWN.CNTY
CONSTANT|OUTPUT||COMP|UNKNOWN.COMP
CONSTANT|OUTPUT||COMPANY|WELL_HEADER.COMPANY
CONSTANT|OUTPUT||COUNT|UNKNOWN.COUNT
CONSTANT|OUTPUT||COUNTY|WELL_HEADER.COUNTY
CONSTANT|OUTPUT||DATE|UNKNOWN.DATE
CONSTANT|OUTPUT||DRMEA|UNKNOWN.DRMEA
CONSTANT|OUTPUT||EPDAT|UNKNOWN.EPDAT
CONSTANT|OUTPUT||ERT|UNKNOWN.ERT
CONSTANT|OUTPUT||FIELD|WELL_HEADER.FIELD
CONSTANT|OUTPUT||FLD|UNKNOWN.FLD
CONSTANT|OUTPUT||LATI|UNKNOWN.LATI
CONSTANT|OUTPUT||LATITUDE|WELL_HEADER.LATITUDE
CONSTANT|OUTPUT||LGMEA|UNKNOWN.LGMEA
CONSTANT|OUTPUT||LOC|UNKNOWN.LOC
CONSTANT|OUTPUT||LOCATION|WELL_HEADER.LOCATION
CONSTANT|OUTPUT||LONG|UNKNOWN.LONG
CONSTANT|OUTPUT||LONGITUDE|WELL_HEADER.LONGITUDE
CONSTANT|OUTPUT||OPERATOR|WELL_HEADER.OPERATOR
CONSTANT|OUTPUT||PDAT|UNKNOWN.PDAT
CONSTANT|OUTPUT||PERMANENT_DATUM|WELL_HEADER.PERMANENT_DATUM
CONSTANT|OUTPUT||RWS|UNKNOWN.RWS
CONSTANT|OUTPUT||SRVC|UNKNOWN.SRVC
CONSTANT|OUTPUT||STATE|WELL_HEADER.STATE
CONSTANT|OUTPUT||STATE|UNKNOWN.STATE
CONSTANT|OUTPUT||TAPE_NAME|UNKNOWN.TAPE_NAME
CONSTANT|OUTPUT||TOOL_STRING|UNKNOWN.TOOL_STRING
CONSTANT|OUTPUT||UTMZ|UNKNOWN.UTMZ
CONSTANT|OUTPUT||WELL_NAME|WELL_HEADER.WELL_NAME
CONSTANT|OUTPUT||WN|UNKNOWN.WN
CONSTANT|OUTPUT||WST|UNKNOWN.WST
LOG|OUTPUT|METRES|DEPTH|UNKNOWN.DEPTH
LOG|OUTPUT|US/F|DTCO3_1|UNKNOWN.DTCO3_1
LOG|OUTPUT|US/F|DTSH5_1|UNKNOWN.DTSH5_1
LOG|OUTPUT|GAPI|ECGR_1|UNKNOWN.ECGR_1
LOG|OUTPUT|DEG|HAZI_1|UNKNOWN.HAZI_1
LOG|OUTPUT|MM|HCAL_1|UNKNOWN.HCAL_1
LOG|OUTPUT|DEG|HDEVI_1|UNKNOWN.HDEVI_1
LOG|OUTPUT|G/C3|RHOZ_1|UNKNOWN.RHOZ_1
LOG|OUTPUT|OHMM|RLA1_1|UNKNOWN.RLA1_1
LOG|OUTPUT|OHMM|RLA2_1|UNKNOWN.RLA2_1
LOG|OUTPUT|OHMM|RLA3_1|UNKNOWN.RLA3_1
LOG|OUTPUT|OHMM|RLA4_1|UNKNOWN.RLA4_1
LOG|OUTPUT|OHMM|RLA5_1|UNKNOWN.RLA5_1
LOG|OUTPUT|OHMM|RT_HRLT_1|UNKNOWN.RT_HRLT_1
LOG|OUTPUT|OHMM|RXOZ_1|UNKNOWN.RXOZ_1
LOG|OUTPUT|V/V|TNPH_1|UNKNOWN.TNPH_1
# 
~A       DEPTH 
